# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef28df3915efdaaf5ca43ab6a4139ed25716c903d344f7703298167cb56b80816145cca0570b40de9e42bb7f993ebf0052384217d61350f1299e4d0df297e60a

test:
  secret_key_base: 8b1531728db511e9b5be068e611884fb780a568db4c84a087d5a3bdf8c9a89218a7aee4f6e9a317290300515fb93967d06261f5c24776e6c1c39da0925fa56b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
